version: '3.8'

services:
  task-queue:
    container_name: task-queue-system
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    command: node src/server.js